=== appfi5/ckb-labels/information/legacy_omiga_inscription/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "symbol": {
      "type": "string",
      "minLength": 1
    },
    "icon": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "decimal": {
      "type": "number",
      "minimum": 0
    },
    "tags": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "rgb++",
              "layer-1-asset",
              "layer-2-asset",
              "supply-limited"
            ]
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "manager": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "type": {
      "type": "object",
      "properties": {
        "codeHash": {
          "type": "string",
          "minLength": 1
        },
        "hashType": {
          "type": "string",
          "enum": [
            "type",
            "data",
            "data1",
            "data2"
          ]
        },
        "args": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "codeHash",
        "hashType",
        "args"
      ],
      "additionalProperties": false
    },
    "typeHash": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "udtType": {
      "type": "string",
      "enum": [
        "sudt",
        "xudt",
        "xudt_compatible",
        "omiga_inscription",
        "ssri"
      ]
    },
    "published": {
      "type": "boolean"
    },
    "email": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "famous": {
      "type": "boolean"
    },
    "operatorWebsite": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "symbol",
    "icon",
    "decimal",
    "tags",
    "manager",
    "type",
    "typeHash",
    "description",
    "udtType",
    "published",
    "email",
    "famous",
    "operatorWebsite"
  ],
  "additionalProperties": false
}

=== appfi5/ckb-labels/information/udt/mainnet/0x73cb97e31030f26299f73d4afb38e4b8ab241adad11c8f1b8fd81727ea3b6b36/index.json
{
  "$schema": "../../schema.json",
  "name": "USDT (Bridged)",
  "symbol": "CUSDT",
  "icon": "logo.png",
  "decimal": 8,
  "tags": null,
  "manager": "ckb1qyqxu8gd0mjkvraz774zkgj3p4ks7mx4fp8sm5rft9",
  "type": {
    "codeHash": "0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5",
    "hashType": "type",
    "args": "0xf951c4f35aabb9b23dff18b1c7e433801ff6d94430d180335082cc65373d1220"
  },
  "typeHash": "0x73cb97e31030f26299f73d4afb38e4b8ab241adad11c8f1b8fd81727ea3b6b36",
  "description": "USDT is a stablecoin (stable-value cryptocurrency) that mirrors the price of the U.S. dollar, issued by a Hong Kong-based company Tether. The tokenâ€™s peg to the USD is achieved via maintaining a sum of dollars in reserves that is equal to the number of USDT in circulation.  CKB-USDT is backed 1:1 with the official ETH-USDT, endorsed by Bitpie.",
  "udtType": "sudt",
  "published": true,
  "email": "ckb-explorer@magickbase.com",
  "famous": true,
  "operatorWebsite": "https://bitpie.com/"
}

=== appfi5/ckb-labels/information/udt/testnet/0x4c05756b3884db104e52291e1f1361e40e9946e637a1ecf66fcb5f74eabc1b92/index.json
{
  "$schema": "../../schema.json",
  "name": "BTD",
  "symbol": "BTD",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qksnrtqfxfvluhjz592wyu0f9jh6n9vd5ny9xepang0p3ar42k04gqqqqqq0a303a",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x12fc0a4a7ee2b1171c216f8119b1fb8dac6caea4296fd15fde6e96bad966f4b2"
  },
  "typeHash": "0x4c05756b3884db104e52291e1f1361e40e9946e637a1ecf66fcb5f74eabc1b92",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x0c3beaf6d33f36b742260930a61a47b4efb611d31a1f4668d508c817caa8df44/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67q4exx4fhs3tc6wdgzltlrtx38ve65v2w0mr3k86c9qt25u8h3nw6sqqqqqqss9e0m",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0xcd32471a878127270f348ced2cf59a06d8a083c0dd909c678f2db17a0100da9a"
  },
  "typeHash": "0x0c3beaf6d33f36b742260930a61a47b4efb611d31a1f4668d508c817caa8df44",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0xc363165b802e2db6e4cae6fc1133174a9f311c3ac9d3d8c994f7c79deda98468/index.json
{
  "$schema": "../../schema.json",
  "name": "QWER",
  "symbol": "QWER",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq05v0t0axsc9mwmyzl6xmqw5s4w0g8q28qhw3f99",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x7b12824f1be0ad6b0587f77819e38625f76fae5bed2bc880e5a84e87f1ad5bfd"
  },
  "typeHash": "0xc363165b802e2db6e4cae6fc1133174a9f311c3ac9d3d8c994f7c79deda98468",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/mainnet/0x6c8fa633bfd8887ff1371fa6219e9a26b68d29aa37cb1e4fde639de0a82f5f28/index.json
{
  "$schema": "../../schema.json",
  "name": "DAI",
  "symbol": "DAI",
  "icon": "https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.svg?v=002",
  "decimal": 18,
  "tags": null,
  "manager": "ckb1qzfmc753t57clzuk0z7xc7sh29ecexwwdenthfxl4dtxwtmddytcjq2lqqqqqyqqqqqrqqqqqqcsqqqqchlf5xgdn70phzppj99mzlgumxjr9p4q5fh5ccee0nda4dn0uxxsz2sqqqqrq7pkggcnwdf5xu6y2wpexqungse5x3zxzwfcvgun2dz9v4jx2s2rxsun2v3hx9jrq3sh79ghw",
  "type": {
    "codeHash": "0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5",
    "hashType": "type",
    "args": "0xdd97fe4f673ed231af188855f4ca8b1034153c8d4e40f5b4fae2afd5d3f53ccc"
  },
  "typeHash": "0x6c8fa633bfd8887ff1371fa6219e9a26b68d29aa37cb1e4fde639de0a82f5f28",
  "description": null,
  "udtType": "sudt",
  "published": true,
  "email": "ckb-explorer@magickbase.com",
  "famous": true,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0xe12a8985454f608724baf37469486103fbbed0f29840b5728786fc5d1b69698b/index.json
{
  "$schema": "../../schema.json",
  "name": "bbbtoken",
  "symbol": "BBBB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qpsu57j8j6jwkxw2fuxsvh9ekyxaeuqz7y8hewupp3cxed4mtseysqgzqqqqqm0sshrj7n7yec3q7skgchah9dqavd8uv99phvlyy6vu0utytuu0xa2y5n",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x8e3dc424d8cb2499bedb30319edecf03b8d0243d8f1834eafb0d8c0166f2cd8e"
  },
  "typeHash": "0xe12a8985454f608724baf37469486103fbbed0f29840b5728786fc5d1b69698b",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/mainnet/0x8328e4b543901b123b17f4e5f5b5af2a98a3901627feddef21a0a539b3a3fe35/index.json
{
  "$schema": "../../schema.json",
  "name": "RBG++",
  "symbol": "RBG++",
  "icon": "logo.png",
  "decimal": 8,
  "tags": [
    "rgb++",
    "layer-1-asset",
    "supply-limited"
  ],
  "manager": "ckb1qz7xc452rgxs5z0ks3xun46dmdp58sepg0ljtae8ck0d7nah945nvqgqqqqqp0k2xzfeldx6qyzmrlkmyhnse26fhq6paumw62dcy4qxs99szjd9ykxecc",
  "type": {
    "codeHash": "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
    "hashType": "data1",
    "args": "0x6e1af00ede836ea45e7ac2fdba8bd9962ffa590112b55b289d081b4a58923471"
  },
  "typeHash": "0x8328e4b543901b123b17f4e5f5b5af2a98a3901627feddef21a0a539b3a3fe35",
  "description": "",
  "udtType": "xudt",
  "published": true,
  "email": "Mhank1028@gmail.com",
  "famous": true,
  "operatorWebsite": "https://explorer.nervos.org/xudts"
}

=== appfi5/ckb-labels/information/legacy_omiga_inscription/testnet/0x2d22b97048f5ed3873496016cad8a8b835ade08e926dadb376e13c27c7f7fbd0/index.json
{
  "$schema": "../../schema.json",
  "name": "CKB Fist Inscription",
  "symbol": "CKBI",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqqyd4v3ahg7q2squ9py3wwf80t8y2dhpl0quppefz",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x6a5a8762fc76d5854e69d8a13611acfede063e77d15e964e3a88660e86cff1af"
  },
  "typeHash": "0x2d22b97048f5ed3873496016cad8a8b835ade08e926dadb376e13c27c7f7fbd0",
  "description": null,
  "udtType": "omiga_inscription",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}
