=== appfi5/ckb-labels/information/legacy_omiga_inscription/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "symbol": {
      "type": "string",
      "minLength": 1
    },
    "icon": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "decimal": {
      "type": "number",
      "minimum": 0
    },
    "tags": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "rgb++",
              "layer-1-asset",
              "layer-2-asset",
              "supply-limited"
            ]
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "manager": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "type": {
      "type": "object",
      "properties": {
        "codeHash": {
          "type": "string",
          "minLength": 1
        },
        "hashType": {
          "type": "string",
          "enum": [
            "type",
            "data",
            "data1",
            "data2"
          ]
        },
        "args": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "codeHash",
        "hashType",
        "args"
      ],
      "additionalProperties": false
    },
    "typeHash": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "udtType": {
      "type": "string",
      "enum": [
        "sudt",
        "xudt",
        "xudt_compatible",
        "omiga_inscription",
        "ssri"
      ]
    },
    "published": {
      "type": "boolean"
    },
    "email": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "famous": {
      "type": "boolean"
    },
    "operatorWebsite": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "symbol",
    "icon",
    "decimal",
    "tags",
    "manager",
    "type",
    "typeHash",
    "description",
    "udtType",
    "published",
    "email",
    "famous",
    "operatorWebsite"
  ],
  "additionalProperties": false
}

=== appfi5/ckb-labels/information/udt/testnet/0x0f630dc10c6eef4689ca456cd4bfc6ae29141f0eef0ae56823edcda669003b89/index.json
{
  "$schema": "../../schema.json",
  "name": "fxxxxxx",
  "symbol": "FXXXX",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsq0xlehxvjeu5n0khdz3gvkavd0n429sthcdv0g8c",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0xf9563d302da153c7f4ddf19fc9a321b77eb4812e2e05c1e29dfefb39d0f886b6"
  },
  "typeHash": "0x0f630dc10c6eef4689ca456cd4bfc6ae29141f0eef0ae56823edcda669003b89",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x73b56ebf21be18fa8c40e0cb830b7cc49f3956235cbc3233016b60cd327060a0/index.json
{
  "$schema": "../../schema.json",
  "name": "people4",
  "symbol": "people4",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qkl8k2v4uyk09wgftw52afvxm0zj3z4gcygj7uzc47uj5hxagwt75qqqqqqpk3mk4",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x5294a021a4c485ce66213ede38d9f13d729eab1041f6dcd8afc4cff6a2ad7e57"
  },
  "typeHash": "0x73b56ebf21be18fa8c40e0cb830b7cc49f3956235cbc3233016b60cd327060a0",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/legacy_omiga_inscription/testnet/0xa6e7a40bcbd91c08e44ecea1f66251b32a02adac9fb41268629caf8536a49070/index.json
{
  "$schema": "../../schema.json",
  "name": "x",
  "symbol": "X",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqqxnf4g0g30zu4pvnrx70ngxqexpqtv7ekcfe7eeq",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x57c4fb93a6c6b1f7dda0b35e1eb552d87d13f6f9e456a398b764cda8277368db"
  },
  "typeHash": "0xa6e7a40bcbd91c08e44ecea1f66251b32a02adac9fb41268629caf8536a49070",
  "description": null,
  "udtType": "omiga_inscription",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x249d63832c8580a406c48e10cd83e4045934db90002005bb53c0db62489600de/index.json
{
  "$schema": "../../schema.json",
  "name": "Magi Test 2",
  "symbol": "Magi3",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqdx68kugk92hz6nguz4dxhghvt0zfusedssyahm7",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x90d640f8452a6e022d6754d6aa2598ab17044b9478cadd0f2f78aafd1b0739fb1117"
  },
  "typeHash": "0x249d63832c8580a406c48e10cd83e4045934db90002005bb53c0db62489600de",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x01093ffe54763822cd7d4beedba111f68a47fcd38bf3959cc03b0929b2816570/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qkp6v46cc5e4adpf5jq5u99d8eupm6sxg2d2zxmhkp0jprhntkdfyqqqqqqss779e",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0xe95e448bec6094276317b40e0b69bf825a7844882d9fe936c817152077605821"
  },
  "typeHash": "0x01093ffe54763822cd7d4beedba111f68a47fcd38bf3959cc03b0929b2816570",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x5942efe9cd0ab0289c9d41760df33d8dd8c152acee423ab876a49b6448d45525/index.json
{
  "$schema": "../../schema.json",
  "name": "Assdd",
  "symbol": "Assdd",
  "icon": null,
  "decimal": 3,
  "tags": null,
  "manager": "ckt1qqkl2w6e9ke6ud59kau84h877qej5cg7mwpu50lv5s6cpxtycwhlyqkn0sj4hlzmn2h2qxdu307lncerr6wjayjk5fzly88gpfgdunjceqcymtdt",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0xfd04ae13a59236682411572e15c1c9627eae1b38fc23194689cc0a4913626cfa"
  },
  "typeHash": "0x5942efe9cd0ab0289c9d41760df33d8dd8c152acee423ab876a49b6448d45525",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/mainnet/0x6f07e3411ed4c39a725828a78727d03814945b4962b976ead9e3831961922b3d/index.json
{
  "$schema": "../../schema.json",
  "name": null,
  "symbol": "LP-UTXOSwap V1",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckb1qrgqep8saj8agswr30pls73hra28ry8jlnlc3ejzh3dl2ju7xxpjxqgqq9v98gvvhzqf8p4xfwnkn8vw4v39jpxy35js8kc3",
  "type": {
    "codeHash": "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
    "hashType": "data1",
    "args": "0x9c1f7b8d38415b95236017342ec3c0b032011bf07476250e131d5f46923ba09400000040"
  },
  "typeHash": "0x6f07e3411ed4c39a725828a78727d03814945b4962b976ead9e3831961922b3d",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0xb2f4021a118c354202926c1d3f32a90644cbab87d159b8e68f00adbf46988c93/index.json
{
  "$schema": "../../schema.json",
  "name": null,
  "symbol": "LP-UTXOSwap V1",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qrejnmlar3r452tcg57gvq8patctcgy8acync0hxfnyka35ywafvkqgyfzpeenxsahfrqlm7zp7s37hhzvj7mu0nqqh7japq",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0xf20d86987a4241225fe3ae2bf9246af5bb7b9f4c120c10fc460019cd1415cbdd00000040"
  },
  "typeHash": "0xb2f4021a118c354202926c1d3f32a90644cbab87d159b8e68f00adbf46988c93",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}
