=== appfi5/ckb-labels/information/legacy_omiga_inscription/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "symbol": {
      "type": "string",
      "minLength": 1
    },
    "icon": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "decimal": {
      "type": "number",
      "minimum": 0
    },
    "tags": {
      "anyOf": [
        {
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "rgb++",
              "layer-1-asset",
              "layer-2-asset",
              "supply-limited"
            ]
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "manager": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "type": {
      "type": "object",
      "properties": {
        "codeHash": {
          "type": "string",
          "minLength": 1
        },
        "hashType": {
          "type": "string",
          "enum": [
            "type",
            "data",
            "data1",
            "data2"
          ]
        },
        "args": {
          "type": "string",
          "minLength": 1
        }
      },
      "required": [
        "codeHash",
        "hashType",
        "args"
      ],
      "additionalProperties": false
    },
    "typeHash": {
      "type": "string",
      "minLength": 1
    },
    "description": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "udtType": {
      "type": "string",
      "enum": [
        "sudt",
        "xudt",
        "xudt_compatible",
        "omiga_inscription",
        "ssri"
      ]
    },
    "published": {
      "type": "boolean"
    },
    "email": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    },
    "famous": {
      "type": "boolean"
    },
    "operatorWebsite": {
      "anyOf": [
        {
          "type": "string"
        },
        {
          "type": "null"
        }
      ]
    }
  },
  "required": [
    "$schema",
    "name",
    "symbol",
    "icon",
    "decimal",
    "tags",
    "manager",
    "type",
    "typeHash",
    "description",
    "udtType",
    "published",
    "email",
    "famous",
    "operatorWebsite"
  ],
  "additionalProperties": false
}

=== appfi5/ckb-labels/information/udt/testnet/0xe0c513ff5302f3cfd3b4c7bbc052200a39cb8a9e7985d9081cac088e2fa807be/index.json
{
  "$schema": "../../schema.json",
  "name": "QL Test Token7",
  "symbol": "QLT7",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqgjetwv0ym8spejhxzaj6g0lqqrrnas4sglswsxy",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x5f85a13c404c69dc7f0c1a35559d8c8bd6919e88f008d420a71acc25720d5a70"
  },
  "typeHash": "0xe0c513ff5302f3cfd3b4c7bbc052200a39cb8a9e7985d9081cac088e2fa807be",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x68fca049a8472f1fd0405b4a62f39421b7bb33d1fd1a1b647076d690d8739631/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67q4mjqmq2jp0ysp0z8c5mr4ja5rslvahu2j9e57rctkp9amhmy93gqqqqqqqw7jvh5",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x45cfdb26d1b9820ddf2ddada9887412d62e3aa6e6c56818aaaf4dfdf84b81f3f"
  },
  "typeHash": "0x68fca049a8472f1fd0405b4a62f39421b7bb33d1fd1a1b647076d690d8739631",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x5637f69738af13293ad6b4d08e96c8ef3297d673d5af371837896f9e8a2e6f13/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qhep3tszetfstdv6n3q40fm93gzufsejshe7q7awnq6fjhgv2dengqqqqqqrpu0d0",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x0b337629b766eff1a5c1edd8b52335f6c56d2b04c8182aab9a40167a55036edc"
  },
  "typeHash": "0x5637f69738af13293ad6b4d08e96c8ef3297d673d5af371837896f9e8a2e6f13",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/mainnet/0x203454c26b31d7ead07bb554d59bc04c1d4f7fd35201965b5532dbead73caa36/index.json
{
  "$schema": "../../schema.json",
  "name": "W",
  "symbol": "W",
  "icon": null,
  "decimal": 4,
  "tags": null,
  "manager": "ckb1qqkl2w6e9ke6ud59kau84h877qej5cg7mwpu50lv5s6cpxtycwhlyq5gvwyk66g6xyj75ry6pq63c863e5x6qry0er6vaqnrs4sha6nrc5a4hsz2",
  "type": {
    "codeHash": "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
    "hashType": "data1",
    "args": "0xe83b41f4500a055b69e042bff81a4d9e6ec634ef24640d4c240ea086685eb920"
  },
  "typeHash": "0x203454c26b31d7ead07bb554d59bc04c1d4f7fd35201965b5532dbead73caa36",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0xd49e3e92c548adde42951d51703378a2677bb7062e7f1c21068c0214d5f121ae/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67q3fcrsvj3u7uj4dtjk65x42flzzjachx9cxvjgmwzuyr2fk3gy4k5qqqqqqu0z0sh",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0xe8a1da9eeb0b9547badab6ef655e920a10fdcd5f376925541c6db33636320af2"
  },
  "typeHash": "0xd49e3e92c548adde42951d51703378a2677bb7062e7f1c21068c0214d5f121ae",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x971f5472ef2efd41c1e6606ec5ac419cd6f987295788cc9f60737daff535ea34/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67q4se69wkfmmky0n7wsrvzgdt00hkugahlu5wnhzv3j5908ysel48sqqqqqqfzw3r8",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x9c359a6f928688ff8b30c99205a3cf471ca3aaf4a5e760e2c27eef321d3b5bf5"
  },
  "typeHash": "0x971f5472ef2efd41c1e6606ec5ac419cd6f987295788cc9f60737daff535ea34",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0x3b8c3a627ebfee83abce0f06a25ddba893a730861f91a42b8cec39ee589d2b3d/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qk7um3aq5447ff6vffdffxwpjyyl4w48rnp9sqytce69ss8xakml5qqqqqqmlevfsckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67qk7um3aq5447ff6vffdffxwpjyyl4w48rnp9sqytce69ss8xakml5qqqqqqmlevfs",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0xe197214ef8f5fffba6326731cdd2908828ecddbf9a5bdae0a7dfcc17d6254bb6"
  },
  "typeHash": "0x3b8c3a627ebfee83abce0f06a25ddba893a730861f91a42b8cec39ee589d2b3d",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}

=== appfi5/ckb-labels/information/udt/testnet/0xa2b239722e342a4f9f5d9cdbaac6c77b0e489808dc5cf095651cf5aebd65206f/index.json
{
  "$schema": "../../schema.json",
  "name": "BTB",
  "symbol": "BTB",
  "icon": null,
  "decimal": 8,
  "tags": null,
  "manager": "ckt1qzpfq3n62yh9hxnts9jxnv8d4wap7jkywn3gllwkqnp203myg6a67q5ejpmh453xkfslh62fc33qjr9vru8cn4lsg7aewxwym7pksy6xysqqqqqqeree28",
  "type": {
    "codeHash": "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
    "hashType": "type",
    "args": "0x214b25f6f33f5fda6e2447f3c8409ab13dfac694110541554a0798cece68f609"
  },
  "typeHash": "0xa2b239722e342a4f9f5d9cdbaac6c77b0e489808dc5cf095651cf5aebd65206f",
  "description": null,
  "udtType": "xudt",
  "published": true,
  "email": null,
  "famous": false,
  "operatorWebsite": null
}
